[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tec5"
version = "0.2.0"
description = "Thin Python bindings for the tec5 SDACQ acquisition library"
authors = [{name = "Jason Doar", email="jbdoar@gmail.com"}]
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.12"

dependencies = []

[project.urls]
Repository = "https://github.com/jbdoar/tec5"

[tool.setuptools.packages.find]
where = ["src"]
